### ISSUE TITLE
Where can I get the animals dataset for the training script ?

### ISSUE THREAD

**Issue by Rituraj-commits** [oke-aditya/image_similarity#5]

**Comment by oke-aditya** [comment]
Nice doubt. But the code is very generic it will work fine for any dataset folder.
The folder needs images labelled from `0, 1, 2, ...` and so on.

I had a small dataset of 500 images all of size 512 x 512 (I think).

**Comment by Rituraj-commits** [comment]
Okk I have implemented with my own dataset. Thanks !

**Comment by oke-aditya** [comment]
https://www.kaggle.com/datasets/okeaditya/animals-data
