### ISSUE TITLE
Where can we get the sample dataset you use? Or could you share about the conditions the dataset should satisfy?

### ISSUE THREAD

**Issue by ys0923** [oke-aditya/image_similarity#6]
Tutorials are in `.ipynb` format, explaining each step of the process, really detailed, not production like.  

Examples are be in the `.py` format, more production oriented. Ready to be run with arguments from the command line and easy to integrate with wandb sweeps and alike.  

It should be an open dataset, please provide the link.

**Comment by oke-aditya** [comment]
Hi @ys0923,

Thanks for the issue.
 
I think that there have been many queries for the dataset as well as a training example.
I had a very simple dataset of images with size 512x512x3 = (3, 512, 512) Tensor.
It had different types of animals in the dataset. Namely (Tiger, Lion, Cheetah and wolf)

The code is very generic it will work fine for any dataset folder.

The folder needs images labelled from 0, 1, 2, ... and so on.

Sadly I don't have a copy of dataset with me :cry: and hence I really cannot provide a kaggle kernel.

Can you try training on one maybe if you have sufficient bandwidth, more than 20 epochs or so?

Also see #5

The code has worked fine for many people. So I suppose it should satisfy your use case too.
Note that this model is very basic and really like an AlexNet, so no huge expectations for training / results.

**Comment by oke-aditya** [comment]
https://www.kaggle.com/datasets/okeaditya/animals-data
